apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: nginx
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gke-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
