
apiVersion: v1

kind: Service

metadata:

 name: gke-test

spec:

 selector:

 app: md-deployment-app1

 type: LoadBalancer

 ports:

 - port: 80

 targetPort: 80

---

apiVersion: apps/v1

kind: Deployment

metadata:

 name: mohit-service-new

 namespace: mohit-test

spec:

 selector:

 matchLabels:

 app: md-deployment-app1

replicas: 4

strategy:

 type: RollingUpdate

 rollingUpdate:

 maxUnavailable: 1

 maxSurge: 1

template:

 metadata:

 labels:

  app: md-deployment-app1

  env: dev

spec:

 containers:

 - name: hello-mohit

   image: nginx

   resources:

    limits:

     cpu: 100m

     memory: 250Mi

   requests:

     cpu: 10m

     memory: 125Mi

  ports:

  - containerPort:
    protocol: TCP

  livenessProbe:

   httpGet:

    port: 80

  initialDelaySeconds: 15
 
  timeoutSeconds: 1

 readinessProbe:

  httpGet:

   port: 80

  initialDelaySeconds: 0

  timeoutSeconds: 1
