
apiVersion: v1

kind: Service

metadata:

 name: gke-test

spec:

 selector:
  app: web

 

 type: LoadBalancer

 ports:

 - port: 80

   targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: nginx
          image: nginx
          ports:
           —containerPort: 80

 
