
apiVersion: v1

kind: Service

metadata:

 name: gke-test

spec:

 selector:

 app: md-deployment-app1

 type: LoadBalancer

 ports:

 - port: 80

 targetPort: 80

---

apiVersion: apps/v1

kind: Deployment

metadata:

 name: gke-test

 spec:

 selector:

 matchLabels:

 app: md-deployment-app1

replicas: 4

strategy:

 type: RollingUpdate

 rollingUpdate:

 maxUnavailable: 1

 maxSurge: 1

template:

 metadata:

  labels:

   app: md-deployment-app1
   env: dev
 spec:

  containers:

  - name: hello-mohit

    image: nginx
    
    ports:

    - containerPort:
      protocol: TCP

 
