
apiVersion: v1

kind: Service

metadata:

 name: gke-test

spec:

 selector:
  env: dev

 

 type: LoadBalancer

 ports:

 - port: 80

 targetPort: 80

---

apiVersion: apps/v1

kind: Deployment

metadata:

 name: gke-test

 spec:

 selector:

 matchLabels:

  env: dev

replicas: 4

strategy:

 type: RollingUpdate

 rollingUpdate:

 maxUnavailable: 1

 maxSurge: 1

template:

 metadata:

  labels:

   
   env: dev
 spec:

  containers:

  - name: hello-mohit

    image: nginx
    
    ports:

    - containerPort:
      protocol: TCP

 
