steps:
- id: auth
  uses: google-github-actions/auth@v0.4.0
  with:
    workload_identity_provider: 'projects/37299108972/locations/global/workloadIdentityPools/test-pool/providers/test-provider''
    service_account: 'my-service-account@coastal-run-379413.iam.gserviceaccount.com'
- id: get-gke-credentials
  uses: google-github-actions/get-gke-credentials@v0.4.0
  with:
    cluster_name: my-cluster
    location: us-central1-a

- id: get-pods
  run: kubectl get pods
